version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "ci(rust)"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      development-dependencies:
        dependency-type: "development"
        applies-to: version-updates
      production-minor:
        dependency-type: "production"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "ci(python)"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      dev-dependencies:
        patterns:
          - "pytest"
          - "maturin"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    labels:
      - "dependencies"
      - "node"
    commit-message:
      prefix: "ci(node)"
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      development-dependencies:
        dependency-type: "development"
        applies-to: version-updates
      production-minor:
        dependency-type: "production"
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 100
    commit-message:
      prefix: ci
    cooldown:
      default-days: 5
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
    groups:
      actions:
        patterns:
          - "*"
        applies-to: version-updates
